name: Build package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependency manager
        run: pip install poetry
      - name: Validate project configuration
        run: poetry check
      - name: Install project dependencies
        run: poetry install
      - name: Build the package
        run: poetry build