name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install the dependency manager
        run: pip install poetry
      - name: Install the project dependencies
        run: poetry install
      - name: Run the linter
        run: poetry run python -m black tap_hellobaton
      - name: Run type checking
        run: poetry run python -m mypy -p tap_hellobaton