name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install black mypy
      - run: python -m black tap_hellobaton
      - run: python -m mypy -p tap_hellobaton
      



    